apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: saswatcloud/p10-ecommerce-inventory-service:8
          ports:
            - containerPort: 8080
          env:
          - name: MONGO_URL
            value: mongodb://mongodb-service:27017/billing
          - name: PRODUCT_SERVICE_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: service-config
                key: PRODUCT_SERVICE_BASE_URL
