apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: saswatcloud/p10-ecommerce-notification-service:4
          ports:
            - containerPort: 8080
          env:
          - name: MONGO_URL
            value: mongodb://mongodb-service:27017/notification
